name = "furniture-orders-mvp"
compatibility_date = "2026-05-29"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "furniture_orders"
database_id = "2f5eddec-b27c-4a05-a1aa-18c18e95ae5b"
